Company registration
Lumory/Lumory pull request #22
Opened 2023-01-16 11:38 UTC by timrebergen

Bedrijfsregistratie werkt nu. Alle input wordt verstuurd naar de back-end

2023-01-18 09:28 UTC, FinndeJong requested changes
Kijk ff naar de comment

2023-01-18 09:28 UTC, FinndeJong commented on Lumory/appsettings.Development.json
> -    "DefaultConnection": "server=lumory-mariadb;user=root;password=password;database=lumory"
Dit moet je weer terug zetten

2023-01-18 10:42 UTC, timrebergen commented on Lumory/appsettings.Development.json
> -    "DefaultConnection": "server=lumory-mariadb;user=root;password=password;database=lumory"
Zou nu weer goed moeten zijn :)

2023-01-19 11:25 UTC, FinndeJong approved these changes

2023-01-19 11:25 UTC, merged