Lum 206 studenten registratie
Lumory/Lumory pull request #9
Opened 2022-12-15 10:36 UTC by mitchellvdhut

2022-12-15 10:51 UTC, FinndeJong commented on frontend/components/Questionaire/MultipleChoiceQuestion.vue
> +@media (min-width: 640px) {
Lege media query?

2022-12-15 10:52 UTC, FinndeJong commented on frontend/components/Questionaire/Step1.vue
> +@media (min-width: 640px) {
Lege media query

2022-12-15 11:05 UTC, FinndeJong requested changes

2022-12-15 11:05 UTC, FinndeJong commented on frontend/components/Questionaire/Stepper.vue
> +      <ol class="c-stepper">
c-stepper c?

2022-12-15 11:05 UTC, FinndeJong commented on frontend/components/Stepper.vue
>      <div class="wrapper option-1 option-1-1">
Vraagtekens bij Class names

2022-12-23 10:30 UTC, timrebergen approved these changes
Code ziet er naar mijn inzicht goed uit. Zou alleen wel in de stepper component nog kijken of je hierin Naive UI components kan toepassen en geen html gebruiken. Tenzij je hierop een toelichting kan bieden waarom je dat op die manier heb gedaan. Voor de rest is alles toppie!

2022-12-23 15:47 UTC, FinndeJong approved these changes

2022-12-23 15:47 UTC, merged